//import with absolute rute using "@/"
import Navigation from "@/components/Navigation";
import "./globals.css";

export const metadata = {
  title: "My First Next App",
  description: "Generated by create next app",
  keywords: ["nextjs", "react", "app"],
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <h1>Navigation</h1>
       <Navigation />
        {children}
      </body>
    </html>
  );
}
